import {
  SearchX,
  Home,
  ChevronRight,
  ChevronDown,
  Cookie,
  Tag,
  StickyNote,
  Landmark,
  ArrowRight,
  ArrowLeft,
  Phone,
  CircleCheckBig,
  Target,
  AlertCircle,
  Send,
  Search,
  User,
  X,
  Menu,
  Mail,
  Info,
  Clock,
  MapPin,
  FileText,
  Check,
  Lock,
  Upload,
  FlaskConical,
  LayoutDashboard,
  ClipboardCheck,
  FilePen,
  Bell,
  Lightbulb,
  RefreshCw,
  LayoutGrid,
  ThumbsUp,
  Calendar,
  Building2,
  Flag,
  AlertTriangle,
  Fingerprint,
  GraduationCap,
  Hospital,
  Store,
  Badge,
  Wallet,
  Baby,
  Car,
  Heart,
  Flame,
  Gavel,
  Shield,
  PersonStanding,
  LogIn,
  Circle,
  WalletCards,
  Contrast,
  Type,
  Zap,
  Mic,
  Keyboard,
  Moon,
  Sun,
  Eye,
  Volume2,
  MousePointer,
  LogOut,
  Headset,
  Bot,
  type LucideIcon,
} from 'lucide-react';

const iconMap: Record<string, LucideIcon> = {
  search_off: SearchX,
  home: Home,
  chevron_right: ChevronRight,
  expand_more: ChevronDown,
  cookie: Cookie,
  tag: Tag,
  sticky_note_2: StickyNote,
  account_balance: Landmark,
  account_balance_wallet: WalletCards,
  arrow_forward: ArrowRight,
  arrow_back: ArrowLeft,
  call: Phone,
  phone: Phone,
  phone_in_talk: Phone,
  check_circle: CircleCheckBig,
  track_changes: Target,
  error: AlertCircle,
  send: Send,
  search: Search,
  person: User,
  close: X,
  menu: Menu,
  email: Mail,
  info: Info,
  schedule: Clock,
  location_on: MapPin,
  description: FileText,
  check: Check,
  lock: Lock,
  upload_file: Upload,
  science: FlaskConical,
  dashboard: LayoutDashboard,
  task: ClipboardCheck,
  task_alt: ClipboardCheck,
  edit_document: FilePen,
  notifications: Bell,
  lightbulb: Lightbulb,
  update: RefreshCw,
  apps: LayoutGrid,
  thumb_up: ThumbsUp,
  calendar_today: Calendar,
  apartment: Building2,
  business: Building2,
  flag: Flag,
  report_problem: AlertTriangle,
  warning: AlertTriangle,
  log_out: LogOut,
  support_agent: Headset,
  robot: Bot,
  fingerprint: Fingerprint,
  school: GraduationCap,
  local_hospital: Hospital,
  storefront: Store,
  badge: Badge,
  child_care: Baby,
  elderly: Heart,
  directions_car: Car,
  fire_truck: Flame,
  gavel: Gavel,
  home_work: Home,
  local_police: Shield,
  person_standing: PersonStanding,
  login: LogIn,
  pending: Clock,
  radio_button_unchecked: Circle,
  contrast: Contrast,
  text_increase: Type,
  animation: Zap,
  record_voice_over: Mic,
  keyboard: Keyboard,
  dark_mode: Moon,
  light_mode: Sun,
  visibility: Eye,
  volume_up: Volume2,
  mouse: MousePointer,
};

export function Icon({
  name,
  size = 24,
  className,
}: {
  name: string;
  filled?: boolean;
  className?: string;
  size?: number;
}) {
  const LucideIcon = iconMap[name] ?? AlertCircle;
  return <LucideIcon size={size} className={className} aria-hidden="true" />;
}
